-- Select database
USE keanwwiiscrapbook_db;

-- Create Authors Table
CREATE TABLE authors(
  id INTEGER PRIMARY KEY,
  last_name VARCHAR(300) DEFAULT NULL,
  first_name varchar(300) DEFAULT NULL,
  middle_name varchar(300) DEFAULT NULL,
  suffix varchar(10) DEFAULT NULL,
  nick_name varchar(300) DEFAULT NULL,
  new_last_name varchar(300) DEFAULT NULL,
  sex varchar(10) DEFAULT NULL,
  service_branch varchar(300) DEFAULT NULL
);

-- Add authors to Authors Table
INSERT INTO authors(id, last_name, first_name, middle_name, suffix, nick_name, new_last_name, sex, service_branch)
VALUES ("1","Ackerman","Howard","Louis","","","","M","Army"),
("2","Allen","Rufus","Bent","Jr.","","","M","Navy"),
("3","Ambry","Edward","Joseph","","Ed","","M","Navy"),
("4","Atterbury","Harold","Blackburn","","","","M","Army Reserve"),
("5","Barone","Henry","J","","Hank","","M","Army Air Corps"),
("6","Bashover","Albert","B","","","","M","Navy"),
("7","Beach","Julia","Catherine","","","Cohen","F","WAAC"),
("8","Behrendt","Robert","Theodore","","Bob","","M","Navy"),
("9","Benisch","Abner","","","","","M","Army"),
("10","Benson","Arthur","Ellsworth","","Art","","M","Army Air Forces"),
("11","Berry","Adelbert","Twitchell","","Del","","M","Army Reserve"),
("12","Bigley","Francis","Vincent","Jr.","","","M","Army"),
("13","Birkner","Frank","Xavier","","","","M","Army"),
("14","Bittman","Walter","Stephen","","","","M","Army Reserve"),
("15","Bizlewicz","Edward","","","Ed","","M","Army"),
("16","Bizlewicz","George","Joseph","","","","M","Army"),
("17","Blum","Bessie","","","","","F","WAAC"),
("18","Bohsen","LeRoy","Andrew","","","","M","Marine Corps"),
("19","Bolinsky","Joseph","Abraham","","Joe","","M","Army"),
("20","Bookstaber","Henry","G","","","","M","Army Air Corps"),
("21","Bosek","Saul","","","","","M","Army"),
("22","Bowman","Arthur","Charles","","","","M","Army Air Corps"),
("23","Brasch","Clarence","Frank","","","","M","Army"),
("24","Braverman","Bernard","","","","","M","Army"),
("25","Brooks","Murray","","","","","M","Army Reserve"),
("26","Bubel","Leon","Louis","","","","M","Marine Corps"),
("27","Buchner","Martin","Stanley","","Stan","","M","Army"),
("28","Cahill","Edward","H","Jr.","","","M","Army"),
("29","Cairns","John","R","","","","M","Army"),
("30","Calcerano","Thomas","","Jr.","Tom","","M","Army"),
("31","Case","Horace","Jonathan","","","","M","Army"),
("32","Christoffel","Frederick","W","","Fred","","M","Army"),
("33","Church","Edward","Riley","","","","M","Army Air Forces"),
("34","Clausen","Robert","W","","Bob","","M","Army Reserve"),
("35","Cloves","John","Wallace","","Wally","","M","Navy"),
("36","Cohen","Emanuel","","","Manny","","M",""),
("37","Coleman","James","John","Jr.","Jim","","M","Army Reserve"),
("38","Cordasco","Rocco","Alfred","","Al","","M","Army Air Corps"),
("39","Cotton","William","","","Bill","","M","Army Air Forces"),
("40","Cummins","Peter","Maurice","","","","M","Army"),
("41","D'Amico","Achilles","Matthew","","Al","","M","Army"),
("42","Daniels","Roy","George","","","","M","Army Infantry"),
("43","DeFinis","Peter","Gerard","","","","M","Army"),
("44","Defino","Frank","Dan","","","","M","Army"),
("45","DeMarzo","Fedele","Frederick","","Fred","","M","Army Air Forces"),
("46","Detgen","Charles","H","","","","M","Army Air Forces"),
("47","Devitt","Wellesley","William","","","","M","Army"),
("48","DeWalsche","James","","","","","M","Naval Reserve"),
("49","DiFazio","Charles","Joseph","","","","M","Army Air Corps"),
("50","DiGiovanni","Vincent","Lewis","","","","M","Army Air Corps"),
("51","Dilks","Charles","Heritage","","","","M","Navy"),
("52","DiPace","Charles","Rocco","","","","M","Army"),
("53","Doherty","Patrick","Richard","","Pat","","M","Army Air Corps"),
("54","Domareki","Joseph","T","","Joe","","M","Navy"),
("55","Donaldson","Warren","W","","","","M","Coast Guard"),
("56","Durante","John","J","","JJ","","M","Army"),
("57","Dykstra","Louis","John","","Lou","","M","Army"),
("58","Earl","Arthur","William","","","","M","Navy"),
("59","Ezekian","Edward","B","","Eddie","","M","Army"),
("60","Fernandez","Paul","J","Jr.","","","M","Army"),
("61","Ferraro","Gerald","Frank","","Gerry","","M","Army"),
("62","Fiore","Benedict","Francis","","Ben","","M","Army"),
("63","Fiore","Joseph","Nicholas","","Nick","","M","Army Air Corps"),
("64","Fiore","Uldric","L","","","","M","Army"),
("65","Flexner","Irving","Lawrence","","","","M","Army"),
("66","Frost","William","E","","","","M","Army"),
("67","Gabry","Thaddeus","S","","Ted","","M","Army"),
("68","Gagnon","Clovis","Roland","","","","M","Army"),
("69","Gathany","Norman","Abbott","","","","M","Army"),
("70","Gelbond","Seymour","Herman","","","","M","Army Air Corps"),
("71","Geller","George","","","","","M","Army"),
("72","Giannuzzi","John","Peter","","","","M","Army"),
("73","Gildner","Edwin","David","","Ed","","M","Army"),
("74","Giunta","Giuseppe","","","Joseph","","M","Army"),
("75","Glaab","James","Arthur","","","","M","Navy"),
("76","Goldberg","Philip","Lionel","","Phil","","M","Army"),
("77","Gorski","Regina","Stella","","","","F","WAAC"),
("78","Gottlieb","Sanford","","","","","M","Army"),
("79","Guritzky","Saul","Shirley","","","","M","Army"),
("80","Guttzeit","Richard","Carl","","Dick","","M","Army Reserve"),
("81","Hale","Joseph","Warren","","Joe","","M","Army"),
("82","Harrell","William","Earl","Jr.","Bob","","M","Army Air Forces"),
("83","Harris","Robert","","","","","M","Army"),
("84","Heeren","Russell","Howard","","","","M","Army"),
("85","Heimlich","Fred","Louis","Jr.","","","M","Naval Reserve"),
("86","Herbert","John","Russell","","Russell","","M","Army Reserve"),
("87","Hill","Ira","H","","","Rosenberg","M","Army"),
("88","Hoagland","Donald","Pierce","","","","M","Army Air Forces"),
("89","Hoffman","Frederick","","","Fred","","M","Army Air Forces"),
("90","Howard","Charles","E","","Charlie","","M","Army"),
("91","Hughes","Richard","","","Dick","","M","Navy"),
("92","Jackman","Walter","Phillips","Jr.","","","M","Navy"),
("93","Jones","Filomena","","","","Fiore","F","Red Cross"),
("94","Kabis","Walter","Lawrence","","","","M","Naval Reserve"),
("95","Kaeppel","Robert","H","","","","M","Army Air Corps"),
("96","Kaufman","Alex","","","","","M","Coast Guard"),
("97","Kaufman","Benjamin","","","Ben","","M","Army Air Corps"),
("98","Keefe","John","","Jr.","Jack","","M","Army Air Corps"),
("99","Kezer","Leonard","James","","Jim","","M","Army"),
("100","Kliman","George","Joseph","","","","M","Army Air Forces"),
("101","Klingler","Edward","A","","Eddie","","M","Army"),
("102","Kowalick","Raymond","","","Ray","","M","Army"),
("103","Krueger","Sidney","","","","","M","Army"),
("104","Kuziora","Chester","T","","Chet","","M","Army"),
("105","Kveder","Leon","Richard","","","","M","Army"),
("106","Landolfi","Carlo","Joseph","","","","M","Army"),
("107","Lay","Howard","Rees","Jr.","","","M","Army Air Corps"),
("108","Lehner","Harold","","Jr.","","","M","Army Reserve"),
("109","Leigh","Sidney","John","","Sid","Liebowitz","M","Army Air Forces"),
("110","Lemerman","Michael","","","Milton","","M","Army"),
("111","Lorusso","Rocco","Eugene","","","","M","Army"),
("112","Lucciola","Theodore","Anthony","","Ted","","M","Army Air Corps"),
("113","Lyon","Louise","P","","","Mann","F","WAVES"),
("114","Lyon","Wesley","William","","","","M","Coast Guard"),
("115","Manganelli","Emily","","","","Davis","F","Red Cross"),
("116","Manna","Ralph","Eugene","","","","M","Army"),
("117","Maron","Stanley","Owen","","Stan","","M","Army"),
("118","Martin","Joseph","Andrew","Jr.","Joe","","M","Army"),
("119","McCarthy","George","F","","","","M","Army Air Forces"),
("120","McCauley","Anne","","","","Watts","F","WAVES"),
("121","Mellberg","Carl","E","Jr.","","","M","Army Air Forces"),
("122","Menweg","William","","","","","M","Army Reserve"),
("123","Metzler","George","J","","","","M","Army"),
("124","Miceli","Anthony","F","","","","M","Army Air Forces"),
("125","Miller","Leon","Gordon","","","","M","Army"),
("126","Mills","Harold","Kenneth","Jr.","","","M","Army Reserve"),
("127","Montgomery","Mervyn","Robert","","","","M","Marine Corps"),
("128","Muniz","Kenneth","Edward","","Ken","","M","Army Air Corps"),
("129","Niemira","Henry","G","","","","M","Army"),
("130","O'Mara","Margaret","","","","Carroll","F","Red Cross"),
("131","Oster","John","","","","","M","Army Air Corps"),
("132","O'Sullivan","Joseph","","","","","M","Army Air Corps"),
("133","Pabst","Francis","Joseph","","","","M","Army"),
("134","Pannullo","Romolo","John","","RJ/Romeo","","M","Army"),
("135","Parkes","Richard","C","","Dick","","M","Army Air Corps"),
("136","Pascucci","Benedict","Gerard","","Ben","","M","Army"),
("137","Paskow","Albert","","","Al","","M","Army Air Forces"),
("138","Peterson","William","Charles","","Bill","","M","Army Air Forces"),
("139","Pezda","Walter","Stanislaus","","","","M","Army Air Forces"),
("140","Phillips","Joseph","W","","","","M","Army Reserve"),
("141","Pichirallo","Joseph","","","","","M","Navy"),
("142","Pierson","Robert","Woodhull","","Bob","","M","Army Reserve"),
("143","Pikus","Joseph","David","","","","M","Army"),
("144","Pollack","Cecil","","","","","M","Army Reserve"),
("145","Polowniak","Peter","Gregory","","","","M","Navy"),
("146","Rasmussen","Louisa","Charlotte","","","","F","Marine Corps"),
("147","Resnick","Abraham","H","","Abe","","M","Army Reserve"),
("148","Roll","Arthur","Frederick","","","","M","Army"),
("149","Romano","Frank","Edward","","","","M","Army Air Corps"),
("150","Rothbard","Albert","","","Al","","M","Navy"),
("151","Ruccione","Albert","","","Al","","M","Army Air Corps"),
("152","Rudnitsky","Gabriel","Gerald","","","Rudney","M","Army Reserve"),
("153","Russo","John","Joseph","","","Russell","M","Navy"),
("154","Russo","William","D","","Bill","","M","Naval Reserve"),
("155","Salkin","Robert","Meyer","","Bob","","M","Naval Reserve"),
("156","Sarnowski","Vincent","Francis","","Vinnie","","M","Naval Reserve"),
("157","Sauer","Alvin","","","Al","","M","Naval Reserve"),
("158","Sauls","Wiley","Paul","Jr.","Paul","","M","Naval Reserve"),
("159","Schaeffer","Jerome","J","","Jerry","","M","Naval Reserve"),
("160","Schneider","Bernhard","W","","Bernie","","M","Naval Reserve"),
("161","Schwartz","Boris","Max","","","","M","Naval Reserve"),
("162","Scott","Alvin","Lyon","","Al","","M","Naval Reserve"),
("163","Sermayan","Charles","","Jr.","","","M","Naval Reserve"),
("164","Shargel","Alfred","","","Al","","M","Naval Reserve"),
("165","Shawcross","Ernest","Charles","","","","M","Naval Reserve"),
("166","Siegel","Harry","","","","","M","Army Air Corps"),
("167","Siegel","Isidore","A","","Is","","M","Army"),
("168","Silverstein","Robert","","","","","M","Army Air Corps"),
("169","Singer","Charles","Edwin Ballou","Jr.","","","M",""),
("170","Smilari","Ferdinand","V","","","","M","Army Air Corps"),
("171","Sollish","Joseph","V","","","","M","Army Air Forces"),
("172","Soraci","Arthur","Robert","","","","M","Army"),
("173","Sozio","Ralph","Pasquale","","","","M","Army Reserve"),
("174","Steuer","Carl","Robert","","","","M","Army"),
("175","Stevens","Charles","","","Charlie","","M","Army"),
("176","Stevens","Edward","John","","","","M","Army Reserve"),
("177","Stout","Joseph","Vanmarter","","","","M","Army Air Forces"),
("178","Talbott","Jane","Beatrice","","","","F","WAVES"),
("179","Tannenbaum","Edward","Edward","","Ed","","M","Army"),
("180","Tansey","Frank","Vincent","Jr.","","","M","Army"),
("181","Tatton","Douglas","W","","Doug","","M","Army Reserve"),
("182","Tetkowski","Clement","Teofield","","","","M","Army"),
("183","Tetkowski","Lenore","","","","Kantor","F",""),
("184","Thompson","Nancy","I","","","","F","No Military Service"),
("185","Tobia","Peter","Ernest","","","","M","Army"),
("186","Trapanese","Menna","Gerard","","","","M","Army Reserve"),
("187","Tunison","Hubert","","","Hugh","","M","Navy"),
("188","Vaughn-Eames","Lenore","","","","","F",""),
("189","Weinik","George","Joseph","","","","M","Army"),
("190","Wilson","Clarence","F","","","","M","Army"),
("191","Unknown Soldier","Other","","","","","M",""),
("192","Various","Other","","","","","",""),
("193","Servicemens News","Other","","","","","","");

