-- Create new database (for local development)
CREATE DATABASE keanwwiiscrapbook_db;
USE keanwwiiscrapbook_db;



-- Create Authors Table
CREATE TABLE authors(
  id INTEGER PRIMARY KEY,
  lastname VARCHAR(300) DEFAULT NULL,
  firstname varchar(300) DEFAULT NULL,
  middlename varchar(300) DEFAULT NULL,
  suffix varchar(10) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  service_branch varchar(300) DEFAULT NULL
);
--- Add authors to Authors Table
INSERT INTO authors(id, lastname, firstname, middlename, suffix, gender, service_branch)
VALUES (1, "Ackerman", "Howard", "", "", "M", "Army"),
(2, "Allen", "Rufus", "", "Jr.", "M", "Navy"),
(3, "Ambry", "Edward", "", "", "M", "Navy"),
(4, "Atterbury", "Harold", "", "", "M", "Army Reserve"),
(5, "Barone", "Henry", "", "", "M", "Army Air Corps"),
(6, "Bashover", "Albert", "", "", "M", "Navy"),
(7, "Beach", "Julia", "Cohen", "", "F", "WAAC"),
(8, "Behrendt", "Robert", "", "", "M", "Navy"),
(9, "Benisch", "Abner", "", "", "M", "Army"),
(10, "Benson", "Arthur", "", "", "M", "Army Air Forces"),
(11, "Berry", "Adelbert", "", "", "M", "Army Reserve"),
(12, "Bigley", "Francis", "", "Jr.", "M", "Army"),
(13, "Birkner", "Frank", "", "", "M", "Army"),
(14, "Bittman", "Walter", "", "", "M", "Army Reserve"),
(15, "Bizlewicz", "Edward", "", "", "M", "Army"),
(16, "Bizlewicz", "George", "", "", "M", "Army"),
(17, "Blum", "Bessie", "", "", "F", "WAAC"),
(18, "Bohsen", "LeRoy", "", "", "M", "Marine Corps"),
(19, "Bolinsky", "Joseph", "", "", "M", "Army"),
(20, "Bookstaber", "Harry", "", "", "M", "Army Air Corps"),
(21, "Bosek", "Saul", "", "", "M", "Army"),
(22, "Bowman", "Arthur", "", "", "M", "Army Air Corps"),
(23, "Brasch", "Clarence", "", "", "M", "Army"),
(24, "Braverman", "Bernard", "", "", "M", "Army"),
(25, "Brooks", "Murray", "", "", "M", "Army Reserve"),
(26, "Bubel", "Leon", "", "", "M", "Marine Corps"),
(27, "Buchner", "Martin", "", "", "M", "Army"),
(28, "Cahill", "Edward", "", "Jr.", "M", "Army"),
(29, "Cairns", "John", "", "", "M", "Army"),
(30, "Calcerano", "Thomas", "", "Jr.", "M", "Army"),
(31, "Case", "Horace", "", "", "M", "Army"),
(32, "Christoffel", "Frederick", "", "", "M", "Army"),
(33, "Church", "Edward", "", "", "M", "Army Air Forces"),
(34, "Clausen", "Robert", "", "", "M", "Army Reserve"),
(35, "Cloves", "John", "", "", "M", "Navy"),
(36, "Cohen", "Emanuel", "", "", "M", ""),
(37, "Coleman", "James", "", "Jr.", "M", "Army Reserve"),
(38, "Cordasco", "Rocco", "", "", "M", "Army Air Corps"),
(39, "Cotton", "William", "Cohn", "", "M", "Army Air Forces"),
(40, "Cummins", "Peter", "", "", "M", "Army"),
(41, "D'Amico", "Achilles", "", "", "M", "Army"),
(42, "Daniels", "Roy", "", "", "M", "Army Infantry"),
(43, "DeFinis", "Peter", "", "", "M", "Army"),
(44, "Defino", "Frank", "", "", "M", "Army"),
(45, "DeMarzo", "Fred", "", "", "M", "Army Air Forces"),
(46, "Detgen", "Charles", "", "", "M", "Army Air Forces"),
(47, "Devitt", "Wellesley", "", "", "M", "Army"),
(48, "DeWalsche", "James", "", "", "M", "Naval Reserve"),
(49, "DiFazio", "Charles", "", "", "M", "Army Air Corps"),
(50, "DiGiovanni", "Vincent", "", "", "M", "Army Air Corps"),
(51, "Dilks", "Charles", "", "", "M", "Navy"),
(52, "DiPace", "Charles", "", "", "M", "Army"),
(53, "Doherty", "Patrick", "", "", "M", "Army Air Corps"),
(54, "Domarecki", "Joseph", "", "", "M", "Navy"),
(55, "Donaldson", "Warren", "", "", "M", "Coast Guard"),
(56, "Durante", "John", "", "", "M", "Army"),
(57, "Dykstra", "Louis", "", "", "M", "Army"),
(58, "Earl", "Arthur", "", "", "M", "Navy"),
(59, "Ezekian", "Edward", "", "", "M", "Army"),
(60, "Fernandez", "Paul", "", "Jr.", "M", "Army"),
(61, "Ferraro", "Gerald", "", "", "M", "Army"),
(62, "Fiore", "Benedict", "", "", "M", "Army"),
(63, "Fiore", "Joseph", "", "", "M", "Army Air Corps"),
(64, "Fiore", "Uldric", "", "", "M", "Army"),
(65, "Flexner", "Irving", "", "", "M", "Army"),
(66, "Frost", "William", "", "", "M", "Army"),
(67, "Gabry", "Thaddeus", "", "", "M", "Army"),
(68, "Gagnon", "Clovis", "", "", "M", "Army"),
(69, "Gathany", "Norman", "", "", "M", "Army"),
(70, "Gelbond", "Seymour", "", "", "M", "Army Air Corps"),
(71, "Geller", "George", "", "", "M", "Army"),
(72, "Giannuzzi", "John", "", "", "M", "Army"),
(73, "Gildner", "Edwin", "", "", "M", "Army"),
(74, "Giunta", "Giuseppe", "", "", "M", "Army"),
(75, "Glaab", "James", "", "", "M", "Navy"),
(76, "Goldberg", "Philip", "", "", "M", "Army"),
(77, "Gorski", "Regina", "", "", "F", "WAAC"),
(78, "Gottlieb", "Sanford", "", "", "M", "Army"),
(79, "Guritzky", "Saul", "", "", "M", "Army"),
(80, "Guttzeit", "Richard", "", "", "M", "Army Reserve"),
(81, "Hale", "Joseph", "", "", "M", "Army"),
(82, "Harrell", "William", "", "Jr.", "M", "Army Air Forces"),
(83, "Harris", "Robert", "", "", "M", "Army"),
(84, "Heeren", "Russell", "", "", "M", "Army"),
(85, "Heimlich", "Fred", "", "Jr.", "M", "Naval Reserve"),
(86, "Herbert", "John", "", "", "M", "Army Reserve"),
(87, "Hill", "Ira", "Rosenberg", "", "M", "Army"),
(88, "Hoagland", "Donald", "", "", "M", "Army Air Forces"),
(89, "Hoffman", "Frederick", "", "", "M", "Army Air Forces"),
(90, "Howard", "Charles", "", "", "M", "Army"),
(91, "Hughes", "Richard", "", "", "M", "Navy"),
(92, "Jackman", "Walter", "", "Jr.", "M", "Navy"),
(93, "Jones", "Filomena", "Fiore", "", "F", "Red Cross"),
(94, "Kabis", "Walter", "", "", "M", "Naval Reserve"),
(95, "Kaeppel", "Robert", "", "", "M", "Army Air Corps"),
(96, "Kaufman", "Alex", "", "", "M", "Coast Guard"),
(97, "Kaufman", "Benjamin", "", "", "M", "Army Air Corps"),
(98, "Keefe", "John", "", "Jr.", "M", "Army Air Corps"),
(99, "Kezer", "Leonard", "", "", "M", "Army"),
(100, "Kliman", "George", "", "", "M", "Army Air Forces"),
(101, "Klingler", "Edward", "", "", "M", "Army"),
(102, "Kowalick", "Raymond", "", "", "M", "Army"),
(103, "Krueger", "Sidney", "", "", "M", "Army"),
(104, "Kuziora", "Chester", "", "", "M", "Army"),
(105, "Kveder", "Leon", "", "", "M", "Army"),
(106, "Landolfi", "Carlo", "", "", "M", "Army"),
(107, "Lay", "Howard", "", "Jr.", "M", "Army Air Corps"),
(108, "Lehner", "Harold", "", "Jr.", "M", "Army Reserve"),
(109, "Leigh", "Sidney", "Liebowitz", "", "M", "Army Air Forces"),
(110, "Lemerman", "Michael", "", "", "M", "Army"),
(111, "Lorusso", "Rocco", "", "", "M", "Army"),
(112, "Lucciola", "Theodore", "", "", "M", "Army Air Corps"),
(113, "Lyon", "Louise", "Mann", "", "F", "WAVES"),
(114, "Lyon", "Wesley", "", "", "M", "Coast Guard"),
(115, "Manganelli", "Emily", "Davis", "", "F", "Red Cross"),
(116, "Manna", "Ralph", "", "", "M", "Army"),
(117, "Maron", "Stanley", "", "", "M", "Army"),
(118, "Martin", "Joseph", "", "Jr.", "M", "Army"),
(119, "McCarthy", "George", "", "", "M", "Army Air Forces"),
(120, "McCauley", "Anne", "Watts", "", "F", "WAVES"),
(121, "Mellberg", "Carl", "", "Jr.", "M", "Army Air Forces"),
(122, "Menweg", "William", "", "", "M", "Army Reserve"),
(123, "Metzler", "George", "", "", "M", "Army"),
(124, "Miceli", "Anthony", "", "", "M", "Army Air Forces"),
(125, "Miller", "Leon", "", "", "M", "Army"),
(126, "Mills", "Harold", "", "Jr.", "M", "Army Reserve"),
(127, "Montgomery", "Mervyn", "", "", "M", "Marine Corps"),
(128, "Muniz", "Kenneth", "", "", "M", "Army Air Corps"),
(129, "Niemira", "Henry", "", "", "M", "Army"),
(130, "O'Mara", "Margaret", "Carroll", "", "F", "Red Cross"),
(131, "Oster", "John", "", "", "M", "Army Air Corps"),
(132, "O'Sullivan", "Joe", "", "", "M", "Army Air Corps"),
(133, "Pabst", "Francis", "", "", "M", "Army"),
(134, "Pannullo", "Romolo", "", "", "M", "Army"),
(135, "Parkes", "Richard", "", "", "M", "Army Air Corps"),
(136, "Pascucci", "Benedict", "", "", "M", "Army"),
(137, "Paskow", "Albert", "", "", "M", "Army Air Forces"),
(138, "Peterson", "William", "", "", "M", "Army Air Forces"),
(139, "Pezda", "Walter", "", "", "M", "Army Air Forces"),
(140, "Phillips", "Joseph", "", "", "M", "Army Reserve"),
(141, "Pichirallo", "Joseph", "", "", "M", "Navy"),
(142, "Pierson", "Robert", "", "", "M", "Army Reserve"),
(143, "Pikus", "Joseph", "", "", "M", "Army"),
(144, "Pollack", "Cecil", "", "", "M", "Army Reserve"),
(145, "Polowniak", "Peter", "", "", "M", "Navy"),
(146, "Rasmussen", "Louisa", "", "", "F", "Marine Corps"),
(147, "Resnick", "Abraham", "", "", "M", "Army Reserve"),
(148, "Roll", "Arthur", "", "", "M", "Army"),
(149, "Romano", "Frank", "", "", "M", "Army Air Corps"),
(150, "Rothbard", "Albert", "", "", "M", "Navy"),
(151, "Ruccione", "Albert", "", "", "M", "Army Air Corps"),
(152, "Rudnitsky", "Gabriel", "Rudney", "", "M", "Army Reserve"),
(153, "Russo", "John", "Russell", "", "M", "Navy"),
(154, "Russo", "William", "", "", "M", "Naval Reserve"),
(155, "Salkin", "Robert", "", "", "M", "Naval Reserve"),
(156, "Sarnowski", "Vincent", "", "", "M", "Naval Reserve"),
(157, "Sauer", "Alvin", "", "", "M", "Naval Reserve"),
(158, "Sauls", "Wiley", "", "Jr.", "M", "Naval Reserve"),
(159, "Schaeffer", "Jerome", "", "", "M", "Naval Reserve"),
(160, "Schneider", "Bernhard", "", "", "M", "Naval Reserve"),
(161, "Schwartz", "Boris", "", "", "M", "Naval Reserve"),
(162, "Scott", "Alvin", "", "", "M", "Naval Reserve"),
(163, "Sermayan", "Charles", "", "Jr.", "M", "Naval Reserve"),
(164, "Shargel", "Alfred", "", "", "M", "Naval Reserve"),
(165, "Shawcross", "Ernest", "", "", "M", "Naval Reserve"),
(166, "Siegel", "Harry", "", "", "M", "Army Air Corps"),
(167, "Siegel", "Isidore", "", "", "M", "Army"),
(168, "Silverstein", "Robert", "", "", "M", "Army Air Corps"),
(169, "Singer", "Charles", "", "Jr.", "M", ""),
(170, "Smilari", "Ferdinand", "", "", "M", "Army Air Corps"),
(171, "Sollish", "Joseph", "", "", "M", "Army Air Forces"),
(172, "Soraci", "Arthur", "", "", "M", "Army"),
(173, "Sozio", "Ralph", "", "", "M", "Army Reserve"),
(174, "Steuer", "Carl", "", "", "M", "Army"),
(175, "Stevens", "Charles", "", "", "M", "Army"),
(176, "Stevens", "Edward", "", "", "M", "Army Reserve"),
(177, "Stout", "Joseph", "", "", "M", "Army Air Forces"),
(178, "Talbott", "Jane", "", "", "F", "WAVES"),
(179, "Tannenbaum", "Edward", "", "", "M", "Army"),
(180, "Tansey", "Frank", "", "Jr.", "M", "Army"),
(181, "Tatton", "Douglas", "", "", "M", "Army Reserve"),
(182, "Tetkowski", "Clement", "", "", "M", "Army"),
(183, "Tetkowski", "Lenore", "Kantor", "", "F", ""),
(184, "Thompson", "Nancy", "", "", "F", "No Military Service"),
(185, "Tobia", "Peter", "", "", "M", "Army"),
(186, "Trapanese", "Menna", "", "", "M", "Army Reserve"),
(187, "Tunison", "Hubert", "", "", "M", "Navy"),
(188, "Vaughn-Eames", "Lenore", "", "", "F", ""),
(189, "Weinik", "George", "", "", "M", "Army"),
(190, "Wilson", "Clarence", "", "", "M", "Army"),
(191, "Unknown Soldier", "Other", "", "", "M", ""),
(192, "Various", "Other", "", "", "", ""),
(193, "Servicemens News", "Other", "", "", "", "");
